name: kookers
description: A new Flutter project.
publish_to: 'none'
version: 1.1.3+12

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Essential packages with null safety support
  rxdart: ^0.27.7
  provider: ^6.1.1
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  enum_to_string: ^2.0.1
  uuid: ^4.3.3
  intl: ^0.20.2

  # GraphQL
  graphql_flutter: ^5.1.2
  graphql: ^5.1.3

  # Firebase packages with null safety
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+8
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6

  # UI packages
  modal_bottom_sheet: ^3.0.0
  chips_choice: ^3.0.1
  flutter_rating_bar: ^4.0.1
  toggle_switch: ^2.3.0
  country_code_picker: ^3.0.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  lottie: ^3.1.0
  badges: ^3.1.2
  flutter_chat_bubble: ^2.0.0

  # Navigation and state management
  get: ^4.6.6
  pull_to_refresh: ^2.0.0

  # Web and networking
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.4
  image_picker: ^1.0.7

  # Maps and location
  google_maps_flutter: ^2.5.3
  # flutter_google_places: ^0.3.0
  # google_place: ^0.4.7  # Conflicts with google_fonts - use geocoding instead
  geocoding: ^2.1.1
  geolocator: ^10.1.0

  # Utilities
  keyboard_actions: ^4.2.0
  rate_my_app: ^2.0.0
  jiffy: ^6.2.1
  flutter_app_badger: ^1.5.0
  package_info_plus: ^5.0.1
  package_info: ^2.0.0
  permission_handler: ^11.3.0
  flutter_native_image: ^0.0.6+1

  # Validation and forms
  iban: ^1.0.1

  # Payment (legacy but needed)
  # stripe_payment: ^1.0.9  # Commented out - consider stripe_ios/android instead

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/payments_logo/
   - assets/onboarding/
   - assets/logo/
   - assets/lottie/
   - assets/translations/